#!/bin/bash

IMMIX="./examples/immix"

#stack exec flp $IMMIX/layout.flp $IMMIX/src/heap/flp/generated.rs \
stack build flp --ghc-options="-ddump-splices"
if [ $? -eq 0 ]; then
  # Add the path of the executable built by stack to PATH instead of installing it:
  export PATH="$(pwd)/$(dirname $(find .stack-work -path */flp/flp | head -n1)):$PATH"
  (cd $IMMIX; cargo build --features "gcbench")
else
  echo "Failed to build FLP."
fi
