#!/bin/bash

IMMIX="./examples/immix"

#stack exec flp $IMMIX/layout.flp $IMMIX/src/heap/flp/generated.rs \

stack build flp --ghc-options="-ddump-splices" \
  && stack install \
  && (cd $IMMIX; cargo build --features "gcbench")

