#resolver: lts-11.14
#resolver: nightly-2018-10-31

#resolver: lts-13.12
#resolver: lts-13.29
#resolver: lts-14.6
#resolver: lts-11.14
#resolver: lts-14.21
resolver: lts-16.0

packages:
- .
  #- ../../../antlr-haskell
  #- location:
  # git: git@github.com:cronburg/antlr-haskell.git
  #  commit: 3e428f7
  #extra-dep: true
  #- location:
  #  git: https://github.com/harpocrates/language-rust
  #  commit: d32e57f
  #extra-dep: true
#- ./deps/language-rust

extra-deps: []
flags: {}
extra-package-dbs: []

