[package]
name = "dist"
version = "0.1.0"
authors = ["Karl Cronburg <karl.cronburg@gmail.com>"]
build = "build.rs"

[build-dependencies]
flp-compiler = { path = "../flp-compiler" }

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
flp-framework = { path = "../flp-framework" }
libc = "0.2.2"

